production:
  flight_alert_checker:
    class: FlightAlertCheckerJob
    queue: alerts
    schedule: every 30 minutes
    
development:
  flight_alert_checker:
    class: FlightAlertCheckerJob
    queue: alerts
    schedule: every 5 minutes
    
test:
  # No recurring jobs in test
